---
- name: Check if ruby installed
  shell: '{{ rbenv_bin }} versions | grep -q {{ ruby_version }}'
  register: ruby_installed
  ignore_errors: yes
  sudo_user: '{{ user_name }}'

- name: Install ruby
  command: '{{ rbenv_bin }} install {{ ruby_version }}'
  sudo_user: '{{ user_name }}'
  when: ruby_installed|failed

- name: Set global ruby version
  command: '{{ rbenv_bin }} global {{ ruby_version }}'
  sudo_user: '{{ user_name }}'

- name: Rehash rbenv
  command: '{{ rbenv_bin }} rehash'
  sudo_user: '{{ user_name }}'

- name: Install bundler
  command: bash -lc "gem install bundler"
  sudo_user: '{{ user_name }}'

- name: Install rails
  command: bash -lc "gem install rails -v '{{ rails_version }}'"
  sudo_user: '{{ user_name }}'